version: "3"

services:
  instagram:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/instagram
    ports:
      - "3000:3000"
    depends_on:
    - db

  db:
    image: 'postgres'
    volumes:
    - '/data/postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
